### ISSUE TITLE
Ordinal highlighter bad placement

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1052]
**Describe the bug**
Using an ordinal x scale on an area/line chart renders incorrect highlight positions.

**To Reproduce**
1. Go to https://codesandbox.io/s/stupefied-swirles-rkq98?file=/src/App.tsx
2. Hover over points
3. Notice the highlighter is off by several ticks

**Expected behaviour**
Highlighter matches the correct actively highlighted bucket

**Screenshots**

https://user-images.githubusercontent.com/19007109/109994781-43100880-7cd3-11eb-9e10-fb2505818e8f.mp4

**Version (please complete the following information):**
 - Elastic Charts: `master`

**Comment by nickofthyme** [comment]
Seems to be fine in `master` storybook but not codesandbox `v25.1.0`

**Comment by markov00** [comment]
It's caused by the applied style in codesandbox. The `text-align:center` style creates this issue and also wrongly centers the legend text.
I've updated the main codesandbox playground template removing completely style
here is the fixed example
https://codesandbox.io/s/objective-hill-rvs5j?file=/src/App.tsx

**Comment by nickofthyme** [comment]
Awesome! Thanks for investigating. Can you update the codesandbox template?

**Comment by markov00** [comment]
@nickofthyme already done it, if you go to the official template: https://codesandbox.io/s/elasticcharts-playground-puj4y
