### ISSUE TITLE
Interactive elements render when chart is not interactive

### ISSUE THREAD

**Issue by spalger** [elastic/elastic-charts#1074]
**Describe the bug**
I'm rendering charts at https://ci-stats.kibana.dev which are not interactive, but the `.echCrosshair__crossLine` and `.echCrosshair__cursor` elements are still rendered, and don't seem to be positioned correctly, causing them to be rendered off to the right of the chart (probably based on the rules of the container or something) requiring that I use `display: none;` to hide these elements.

**To Reproduce**
1. Go to https://ci-stats.kibana.dev/
2. Inspect one of the sparkline charts
3. Look for the `.echCrosshair__crossLine` element and disable the `display: none;` CSS rule in the inspector

**Expected behaviour**
These element probably shouldn't be rendered if the chart isn't interactive, or they should at least be rendered within the container of the chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/1329312/110856408-d49fed00-8274-11eb-9430-14b5f3c592f6.png)

**Version (please complete the following information):**
 - OS: any
 - Browser: Chrome
 - Elastic Charts: 25.1.1

**Comment by markov00** [comment]
The solution should fix these two issues:
- completely remove the SVG elements for crosshair if the interaction is disabled
- we should add the `top` and `left` properties to the `echCrosshair` class because the described behavior is caused by the `text-align:right` style coming from the parent container via `euiStat--rightAligned` class. Our SVGs have a `position:absolute` but no position applied and they are pushed to the right of the subsequent existing element  see https://codesandbox.io/s/misty-forest-7m92u?file=/index.html:304-321.

**Comment by markov00** [comment]
adding a third issue to handle: the tooltip portal `echTooltipPortalMainTooltip__`  should be removed if not tooltip is `None`
