### ISSUE TITLE
[Wordcloud] Replace kibana tagcloud with es-charts 

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#1156]
**Is your feature request related to a problem? Please describe.**
I am currently working on replacing the kibana tagcloud viz with es-charts and I want to report some gaps that exist between the two implementations that need to be addressed. 

- [ ] `onElementClick`: I want to be able to click on a word and get the clicked value. Right now I get:
```
{
    "smAccessorValue": "",
    "groupByRollup": "Word count",
    "value": 9,
    "sortIndex": 0,
    "path": [],
    "depth": 0
}
```
every time I click a word. I would like to get the clicked term. This is needed because we want to trigger the filter action every time a term is clicked.. Moreover, I see that the click event is triggered everywhere and not only when I click a term. (I am fine with it as soon as no term is returned when I click on a blank space). 

- [x] I need to be able to display/hide the label. This label comes from the configuration. It contains the bucket field, the ordering and the metric. I could construct it on the kibana side and just pass it as a prop to the chart. We can further discuss it.

![tagcloud](https://user-images.githubusercontent.com/17003240/117799887-44255f00-b25b-11eb-842e-45b70c412bb0.png)

- [x] Functional tests. I need to check for the following conditions:
- get all the rendered terms
- get the font sizes per term
- be able to select a tag and click it (I can overpass it by clicking a hardcoded x and y but if we can have this info would be awesome)

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/95539

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by monfera** [comment]
Thank you Stratoula! 

1. Label
@markov00 might have a different take, at the moment my preference would be that Kibana supply the chart label (I'd call it a title, but maybe there's a distinct chart title in Kibana above the chart?) because it probably needs application specific labeling (if at all), and its contents are also application specific (eg. should show some total count or not); also, this way there's clarity about internationalization. In fact it may even be preferable to overlay the chart with your own label, because then it'll be inherently part of the accessibility approach on the recipient page. There's also the question of handling text overrun (won't ever happen, let's not bother with it? or truncate with ellipsis? etc.). Looking for your and Marco's feedback on this.

2. Padding
The placement of the label requires space, and assuming that the label render responsibility is with `elastic-charts`, it needs to set aside the appropriate area. It can be handled internally. Even then, is there expectation about leaving a gap of a specific pixel count or chart height ratio between wordcloud proper and title, and below the title?

3. Click event handling
Does the functionality of clicking on a specific word, and getting a callback for just that word work in Kibana? I'm asking it because there are some intricacies. Examples:
very small words might be placed in the crevices between letters of large words
moreover, very small words can even be placed inside other letters, eg. in the letter O, u, etc. if there's enough space
the click doesn't have unambiguous semantics: is it the text ink only? or, for better adherence to Fitts law, the bounding box? but in the latter case, bounding boxes may easily overlap even setting aside the above concerns, because the placement observes the contour of the text, not the bounding box
is the current code doing something to handle overlaps (on the offchance it's not ink based or voronoi based), eg. returning an array of two or more elements?

**Comment by stratoula** [comment]
Update: I implemented the chart label on the kibana side so no need to be supported on the chart.

**Comment by monfera** [comment]
Thanks, Stratoula! So the two pieces of work are, the click event handling, and the provisioning of data for test purposes in the `data-` attribute in the DOM. I'll discuss it with @markov00 next week. Btw. what target date are you looking for these two each, to be aligned with your and your team's priorities?

**Comment by monfera** [comment]
Btw. it's good to hear that the way you configure it in Kibana, there won't be word-in-word occurrence. (For an example of that, see the middle image in the [PR](https://github.com/elastic/elastic-charts/pull/1038) from @Kati-dev-hu - there's text in the "o" of "xobni"). In this case, attaching standard mouse click event handlers on the DOM elements works well. It probably works for the text-in-text case too, as most likely the rendering is ordered in that the big word is layouted first, ie. rendered first, ie. the small item atop of it can still capture the mouse.

**Comment by stratoula** [comment]
>  Btw. what target date are you looking for these two each, to be aligned with your and your team's priorities?

It would be awesome if I could replace the old tagcloud with the es-charts implementation on 7.14 but it is perfectly fine if we merge it on 7.15.

**Comment by markov00** [comment]
my 2 cents:
1. chart title: my preference is to keep it at the moment outside the chart library. You have much more flexibility then having a prop + all the possible styling options in charts
2. click handler: if there is no word-in-word occurrences, then sorting first the rendering + attaching the DOM event to each element should work

**Comment by monfera** [comment]
Indeed, my understanding is that it's already ordered this way by the `d3-cloud` library, so I know of these two tasks:

-attaching the click event handlers onto the SVG `<text>` elements (now glad we went the DOM way on this chart)
- provisioning of data for test purposes in the data- attribute in the DOM

@rshen91 as the vis accessibility powerhouse, it'd be worth taking an initial look at it, as the `ARIA-*` labels can be directly used on each DOM element, if needed

**Comment by stratoula** [comment]
Another update about the functional tests. There is no need to provide me with all this info that I mentioned above. As wordcloud is based on svg I can access the elements and write the functional tests! 
With that being said, the only thing that is missing is the click event per text node.
