### ISSUE TITLE
Heatmap time buckets should use value from timeScale

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1165]
**Describe the bug**
When using the `Heatmap` spec with a time scale, the bucket values are trivial computed and don't always align with the values on the data. This causes charts to render without the cells that should appear the in given domain.

**Expected behavior**
Min and max domain values should be extended to include the full extent of partial buckets. This could be done using the `timeScale.rawTcks`.

**Screenshots**
![image](https://user-images.githubusercontent.com/19007109/119018729-0367cd00-b962-11eb-8340-17533c5df15f.png)

**Version (please complete the following information):**
 - Elastic Charts: `@latest`

This is also related to handling partial time buckets in heatmap. Now lens is just increasing the domain to include the partial buckets as if they were full buckets which is not ideal. See https://github.com/elastic/kibana/pull/97978/files/6283fb0d54cfa1c8e482ffad4b249e294750f02a..356109c161583af3ec60a69be57c2e96e1521cc5#diff-ecf0195846e85c9002680a385d9afe155d27ad5de1c696bdf5f08101201a440fR88-R100

**Kibana Cross Issues**
https://github.com/elastic/kibana/pull/97978#issuecomment-845280585

**Comment by dej611** [comment]
I think this is still broken in some scenarios. At least is really easy to reproduce in Lens with a time range bigger than 2 days.

Here's a Codesandbox with a Lens configuration with the issue: https://codesandbox.io/s/snowy-lake-mesbd?file=/src/App.tsx

I've tested older versions of Kibana and it was broken since the initial release (Kibana 7.15)
