### ISSUE TITLE
[XY Chart] textBorder: false is ignored and values border outline is rendered

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1261]
**Describe the bug**

Setting `displayValue.fill.textBorder = false` to a bar chart makes it show default text white outline.

`0` or not declaring the prop seems to work instead.

**Expected behaviour**
`false` should behave as `0`

**Comment by nickofthyme** [comment]
@monfera has pushed to limit the api to non-union types when practicable. In this case I think setting to `0` is a good option to hide the text border, in fact we do this in many cases for when to render certain styles.

Since the api defines this as `textBorder?: number` and behaves as we expect I will remove the bug label.

**Comment by markov00** [comment]
As enhancement we can definitely check all the API against those erroneous types, but from a TS point of view setting the `textBorder` to `false` should throw an error. Using a number or `undefined` as the accepted type

**Comment by monfera** [comment]
Closing the issue, as the current `fill.borderWidth?: number` doesn't admit `boolean`, at least since your [commit](9b29392631e4ae92db24bb9077a9afacee051318) @dej611 from October 2020 unless TS projects something misleading into Kibana. 

@markov00 the runtime check which I think you mention as the enhancement possibility would be a very broad item, so it'd be worth chatting about it. It has significant implications on 
- code to maintain
- bundle size
- runtime performance and garbage generation
- schema representation (eg. using something like the partitioning `Config` descriptors that also check for range etc

So it feels like too large of a pivot to repurpose this issue for a discussion of this. Also, it feels like the need isn't about the current use case (which TS excels at) but for using automatic configuration UI makers (dat.gui, Lens, test environment, generative tests etc.). We can link such a new issue to this if created.

Pls. feel free to reopen the issue with a comment if I'm overlooking something

**Comment by nickofthyme** [comment]
@dej611 I'm curious how you ran into this issue? Are you working with charts in a javascript file?

**Comment by dej611** [comment]
It was a Typescript file in Kibana Lens. Often the type checker is a bit lazy there, so it didn't pick that up. Or maybe I had an old copy of EC (pre-30.0.0).
