### ISSUE TITLE
[Legends] Discuss: hard to discover shift-click to isolate series

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1339]
**Is your feature request related to a problem? Please describe.**
Not obvious you can shift click to "isolate" a series in a legend. Isolation is really useful if you have a dashboard visualizing many series and one of them is performing abnormally. You may want to quickly filter other visualizations to the same value. 

**Describe the solution you'd like**
Just ideas at this point:
 - Switch the controls: consider if click-to-exclude is really the most important case (or is click-to-isolate more important...this is a discuss issue, so we should discuss. 
 - Come up with a better visual option when hovering a legend series that shows a "thumb tack" and the "eye crossed off" to show there are two options on hover? 
 - There's also some Kibana-level solutions around legend synchronization that we might want to consider

**Describe alternatives you've considered**
Today it works, it's just hard to discover. There's also some awkwardness when "un shift clicking" that results in no visual

**Today's click behavior**
![exclude](https://user-images.githubusercontent.com/5465514/130827916-7eede195-9e6c-40b5-9fd4-3946a7180b6c.gif)

**Today's shift-click behavior**
![isolate](https://user-images.githubusercontent.com/5465514/130827896-5c65d5fa-6c39-4f4a-ab82-ca0b2aece56a.gif)

**Comment by teresaalvarezsoler** [comment]
As per several user feedback click-to-isolate seems to be the expected behaviour and more important than click-to-exclude.     

Solution proposal:
1. Default behaviour should be to click-to-isolate 
2. Show a tooltip "shift + click to exclude" when hovering (it will need to be compatible with the tooltip that appears when labels are truncated)

<img width="357" alt="image" src="https://github.com/elastic/elastic-charts/assets/99645649/65de8703-80da-45f9-ac9c-8667ed6f62a8">

**Comment by markov00** [comment]
hey @MichaelMarcialis what should be a feasible way to implement the tooltip described by Teresa in the second proposed point?
We are using a `title` attribute on the list item that uses the browser's default tooltip.
`EUI` is not an elastic-charts direct dependency so we can't use the EUI tooltip for this and we need to build one or try to reuse the part of what we have already in the chart.

**Comment by MichaelMarcialis** [comment]
> hey @MichaelMarcialis what should be a feasible way to implement the tooltip described by Teresa in the second proposed point?

My initial instinct is to say not to use a tooltip at all. Instead, we could use the existing popover menu (triggered from the right-hand action button) to display both the isolate and exclude actions. Each action could then also show the shortcut used to take that action if they prefer not to use the menu. Something like this:

<img width="1440" alt="shortcut" src="https://github.com/elastic/elastic-charts/assets/3884767/3110cace-b5ac-4172-93a2-b99cfea02868">

Thoughts?

**Comment by markov00** [comment]
This definitely works for me, not sure if that menu is available everywhere, or can be disabled in specific contexts. Definitely is not part of elastic-charts so it will not apply to non-lens charts

**Comment by teresaalvarezsoler** [comment]
Thanks Michael, it looks good to me too.
> Definitely is not part of elastic-charts so it will not apply to non-lens charts
I think that's fine for now.

**Comment by teresaalvarezsoler** [comment]
@MichaelMarcialis now that I think twice about it, I think we are overcomplicating that menu unnecessarily. I don't think users will open that menu to isolate/exclude series, it's too cumbersome. I think it will barely be used.

The discoverability problem to hide series can be solved just showing a tooltip when users hover which is a pretty standard and expected behaviour. What do you think? (cc @dej611 )

**Comment by MichaelMarcialis** [comment]
> @MichaelMarcialis now that I think twice about it, I think we may be overcomplicating that menu unnecessarily. It will be too cumbersome for users to open that menu to isolate/exclude series, don't you think? The discoverability problem to hide series can be solved just showing a tooltip when users hover (as I mentioned [here](https://github.com/elastic/elastic-charts/issues/1339#issuecomment-1943673830)) which is a pretty standard and expected behaviour. Of course you are the UX expert so you have the last decision on this :) (cc @dej611 )

Good question. I think the ultimate intent/hope is that users would only ever need to open that menu once before being educated about the availability of a shortcut to make it easier/faster the next time. In my experience, this feels like a fairly common pattern of accommodating the mouse-centric users while also educating those that prefer shortcuts (all while not adding visual "weight" to the idle experience). For example, Figma does a great job of doing this:

![CleanShot 2024-04-09 at 16 06 01](https://github.com/elastic/elastic-charts/assets/3884767/6abd293e-3826-465a-8200-b1d1977e0484)

Personally, I'd prefer we proceed with the suggested direction rather than the tooltip route, but happy to discuss further if there is a strong case to do so.

**Comment by dej611** [comment]
Can we have an offline sync to discuss this a bit?
I see there are few options on the table and discuss it can help clear out a bit some ambiguity.

I think the decision of what a click and a SHIFT+click should do, and how to provide feedback to the user can have a big impact on the charts library implementation depending on which route we're going into.
