### ISSUE TITLE
[Bar chart] tooltips longer than the page height cause page to jump

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#1576]
**Describe the issue**
Here's the bug raised in Lens: https://github.com/elastic/kibana/issues/122782
When a tooltip is longer than the page, the scroll keeps appearing and disappearing in certain positions:
![Jan-31-2022 13-58-13](https://user-images.githubusercontent.com/4283304/151797717-ab5abe3f-c5d9-428a-8b7f-a89d43a7be43.gif)

Here's the reproducible sandbox (the buggy versions are 35.0.0+)
https://codesandbox.io/s/jumpingscroll-35-0-w6sup

Here's the 34.2.1 version, the working one:
https://codesandbox.io/s/jumpingscroll-34-2-g256r

**Comment by markov00** [comment]
this will be fixed with #615

**Comment by markov00** [comment]
@mbondyra I've tested the example you mentioned working but it doesn't seem to work to me.

With the new tooltip redesign, this bug will be fixed, but we can't fix it with the current version because this problem depends on the style applied to the `body`. The tooltip DOM is attached to the `body` so if the body `overflow` prop is auto/default then the page will scroll and we can't do much (I actually don't have ideas, I really like to avoid testing for the tooltip size to reducing it size depending on the window before rendering it first because this is expensive, second because it is an edge case, third because it can be fixed by the application using the chart itself, and finally because this will be fixed in the near future with the new tooltip design
