### ISSUE TITLE
Display y0 and y1 names on tooltip for band charts

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#162]
A band area chart tooltip does't display two different names for the y0 and y1 value.
The same happens for a bar chart with y0 accessors, it will display only the y1 value.

**Comment by nickofthyme** [comment]
Related to #163

**Comment by nickofthyme** [comment]
@cchaos Could you comment on how this should be styled? It's basically when we have a banded area or bar series and how to display the lower and upper bounds in the tooltip and legend (#163).

The way it is setup now the tooltip would have two labels and two values like this and the label would distinguish them.

<img width="216" alt="Screen Shot 2019-09-24 at 1 16 04 PM" src="https://user-images.githubusercontent.com/19007109/65539031-4132fa80-dece-11e9-85df-b7bc3bf64eb1.png">

But I am thinking it would be better if we kept them as one series and stacked the values in some way. This would be better for the legend too because I want to avoid having two legend values, mainly to avoid hiding and showing of the upper and lower bounds which doesn't really make sense. Also the dual label is a little redundant.

I'm thinking something like below.

<img width="222" alt="Screen Shot 2019-09-24 at 1 17 51 PM" src="https://user-images.githubusercontent.com/19007109/65539251-ab4b9f80-dece-11e9-826b-9c874e6caed1.png">

<img width="220" alt="Screen Shot 2019-09-24 at 1 19 41 PM" src="https://user-images.githubusercontent.com/19007109/65539258-adadf980-dece-11e9-83db-490301d2fcdb.png">

**Comment by cchaos** [comment]
Visually I would love to see the values in the tooltip be represented in the similar order to the one on the graph.

```
area - upper          17.22
average                9.92
area - lower           3.12
```

**Comment by nickofthyme** [comment]
Ooo that will be a little difficult since `area` and `average` are completely separate series.

If we were able to do it this way that would create 2 legend entries which I only think there should be one so we don't allow toggling the upper and lower bounds separately.

What would be your second option, if this is not possible?

**Comment by cchaos** [comment]
Then I'd just write it out as upper and lower.
