### ISSUE TITLE
Compatibility with React 17

### ISSUE THREAD

**Issue by homeyjd** [elastic/elastic-charts#1638]
We are heavy ElasticSearch and elastic-charts users. Great library, guys!

Just one major downside: `package.json` is locked to `"react": "^16.0.0"`, which means we can't upgrade to React 17 (required for many latest libraries, including Material UI v5).

Any challenges with making this `"^16.0.0|^17.0.0"`?

**Comment by nickofthyme** [comment]
Yeah totally, I think upgrading to `react@17` would be fine. EUI has recently upgraded to `react@17` in https://github.com/elastic/eui/pull/5584.

**Comment by homeyjd** [comment]
Hey team!
We are in the process of upgrading to React17 next week. We can clone-and-self-host to add this `react@^17` dependency, but would really prefer to use the pure source.
Any chance we can get this updated in `package.json` asap?

**Comment by spalger** [comment]
I've been using @elastic/charts with React 18 for a while now and it works great. The only issue now (besides the peer dep warnings) is that React 18 types have been updated to require explicitly opting-in to the `children` prop and/or the `ref` prop. Because of this I've had to start using `@ts-expect-error` comments and would love if `@elastic/charts` could update to support or even require React 18. Should be a very easy upgrade for people and doing it in a new major would only require the upgrade for people who are actively upgrading deps anyway.

**Comment by nickofthyme** [comment]
Oh yeah you're right, the original request was to support `react@^17` but think it's okey to allow `18` as well. I'll open another PR.

**Comment by damikun** [comment]
@nickofthyme  did you open issue for react 18 compatibility ?

**Comment by nickofthyme** [comment]
Just created #1743 and just opened #1744
