### ISSUE TITLE
[Mosaic] Lengthy Column Labels Are Omitted

### ISSUE THREAD

**Issue by MichaelMarcialis** [elastic/elastic-charts#1735]
**Is your feature request related to a problem? Please describe.**

For mosaic visualizations in Lens, if the second “Group by” dimension values are overly lengthy, the visualization’s column labels appear to be omitted entirely. This makes the visualization more difficult to parse and requires users hover the visualization to understand what each column represents.

![image](https://user-images.githubusercontent.com/3884767/176511763-b10e8379-e960-4171-b636-cae4736728db.png)

**Describe the solution you'd like**

 My initial instinct is to simply ask that we support label truncation rather than complete omission.

**Describe alternatives you've considered**

Another alternative could be supporting line breaks for lengthy column labels, though that may not look as nice in all situations and/or may require additional controls for allowing users to define the number of lines to show before truncation (similar to how Lens does for legends).

CCing @gvnmagni, @markov00, @flash1293, @ghudgins.

**Comment by markov00** [comment]
The text truncation/clipping is already available using the `clipText` configuration on the first most layer.
<img width="397" alt="Screenshot 2022-07-01 at 00 46 15" src="https://user-images.githubusercontent.com/1421091/176790942-5f0cd5b5-3042-4905-afa8-5f3e625121d7.png">
The truncation is a pure clipping, and it doesn't add an ellipsis in the text.

If you instead, don't clip, the text can go to multi-line already but depends on the minFontSize configured because it needs to shrink to be rendered in the same space.
<img width="482" alt="Screenshot 2022-07-01 at 00 45 43" src="https://user-images.githubusercontent.com/1421091/176791293-198df844-5f95-4010-8f71-9703f6dc73ad.png">


Currently, there isn't an optimized way between these configuration: go multiline until is not possible and then start clipping, but we can think about it.

**Comment by flash1293** [comment]
@markov00 Something is not working right with `clipText` - this is how it looks in Lens when using `clipText: true`:
<img width="1467" alt="Screenshot 2022-07-04 at 11 43 14" src="https://user-images.githubusercontent.com/1508364/177128793-2bba3ed8-15bd-4266-9b48-b8dbf2d5c3f1.png">

This is `clipText: false`:
<img width="1450" alt="Screenshot 2022-07-04 at 11 43 27" src="https://user-images.githubusercontent.com/1508364/177128830-61dfb78a-c85b-4e4f-8a9a-111a2708fdfb.png">

Do you have an idea what this could be caused by?

> go multiline until is not possible and then start clipping

It's more complex, but this sounds like the best approach to me

**Comment by markov00** [comment]
To use `clipText` the `minFontSize` and `maxFontSize` should be configured to be the same, if not the font scale reduction algo kicks in

**Comment by flash1293** [comment]
Makes sense - @ghudgins @gvnmagni how should we configure mosaic for Lens and is the current elastic-charts behavior sufficient?

**Comment by flash1293** [comment]
@markov00 How can `minFontSize` be configured? I can't find it in the types (only for wordcloud)

**Comment by markov00** [comment]
Is a property of the root `layer` in the `fillLabel`
```
layers={[
          {
            groupByRollup: (d: Datum) => d.sitc1,
            nodeLabel: (d: Datum) => productLookup[d].name,
            fillLabel: {
              fontWeight: 100,
              fontStyle: 'italic',
              minFontSize: 10,
              maxFontSize: 10,
              clipText: true,
              valueFont: {
                fontFamily: 'Menlo',
                fontStyle: 'normal',
                fontWeight: 900,
              },
            },
```

**Comment by markov00** [comment]
Close as the configuration is now used in Kibana
