### ISSUE TITLE
Chart `size` attribute type doesn't support "100%" as a valid size

### ISSUE THREAD

**Issue by simianhacker** [elastic/elastic-charts#177]
**Describe the bug**

The `size` attribute definition only supports numbers BUT it should support both `string` and `number` so the user can define something like:

```jsx
<Chart size={['100%', 400]}>...</Chart>
```
This actual works the only issue is Typescript throws a linting error.

**To Reproduce**

1. Create a chart with a size set to `['100%', 400]`
2. Watch Typescript complain
3. Make sad trombone sound with mouth :(

**Expected behavior**

Shouldn't throw typescript error when defining width or height as `"100%"`

**Comment by markov00** [comment]
@simianhacker thanks for reporting this.
Is not bug but it was designed to accept only `numbers`. Typescript complains because the type of the `size` prop is `size?: [number, number]` but if you just ignore it typescript doesn't do anything to force that as it just check that at compile time, not a runtime.

We will update that to a simpler api like `width` and `height` as separated props where, not specified, it always implies `100%`.

For the moment you can easily configure the size of the parent container to the size you like and the chart will adapt to that size:
```
<div class="chartContainer" style={{width: 100%, height: 400}}>
   <Chart/>
</div>
```

**Comment by simianhacker** [comment]
@markov00 Thanks... being able to set the `width` and `height` and defaulting to `100%` when omitted would be ideal.
