### ISSUE TITLE
Metric vis pagination support

### ISSUE THREAD

**Issue by andrewctate** [elastic/elastic-charts#1785]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to view metric tiles in pages when there are large numbers of metrics. Otherwise the metric grid can grow very large.

**Describe alternatives you've considered**
We currently enable scrolling in the Lens metric when the metric grid gets too large. This works, but we thought this pagination idea was worth discussing.

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Hi @andrewctate I see some issues with the pagination and I'm not fully in favour of adopting it, but I'm happy to change my mind if we have some solid reasons for it.

In particular the problem I see with pagination are the following:
- pagination means having different pages/views and never have the ability to compare/see the overall picture at the same time. If you create a grid of metrics is because you want to visualize all of them at once. Introducing pagination cause you to miss some, probably important, metrics because they are on the other page.
- sorting of metric play a big role with pagination, depending on the sorting the important metrics can be hidden easily from the main view
- A dashboard is meant to be used within a single page (not even the scroll should be used, similarly to the reason exposed above). If we include also pagination this split the user vision about the dashboard into multilayer pages, increasing the difficulties to spot important information
- if you need pagination, you are probably not using the right chart, you are currently looking to display too many information on a single page and the medium in this case is not the optimized one. At that point you could select a table to make the same exact functionality with less real estate.

**Comment by andrewctate** [comment]
@markov00 I wanted to record the idea from earlier conversations in this issue but I think your reasoning makes sense. I don't hear anyone really pushing for pagination in the metric chart at the moment.

I think we can close this for now and reopen if there's interest/justification later.
