### ISSUE TITLE
Allow series color to be defined at spec level

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#179]
**Is your feature request related to a problem? Please describe.**
Currently a series chart element gets its color from either our internal color palette (which is assigned by index of the series) or from `customSeriesColors`; both of these color specifications operate on each individual series (so if a series is defined with a splitAccessor, it will provide a color for each subseries).

We expose `stroke` in `lineSeriesStyle`, but defining a value for it does not currently affect the color of the lines of a series.  

**Describe the solution you'd like**
We can implement the charts to support the series-level color specifications such that:

* `customSeriesColors` takes precedence; if a series color is also defined, use the color defined in `customSeriesColors`.
* if `customSeriesColors` does not have a color for a series and series color is defined, use the series color (instead of the color from the internal palette).  This can have the effect that if a series has splitAccessors defined and renders distinct subseries, all of the subseries elements will have that same color.
* if neither `customSeriesColors` nor a series color is defined, use the color from the internal palette.

**Describe alternatives you've considered**
Could also just disable the color-related props for series styling configs.

**Additional context**

**Kibana Cross Issues**
N/A

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
We could eventually also add a slightly different object for the `customSeriesColors` what is can be either a string or a Map? if a string, it will apply to all series, if a map will map to single series.
I think this can be very useful instead of going through the full series style. If we choose this way, we could remove the stroke color from the line stile.

I think in general we should have to provide some nice simple methods to configure styles for single or multiple colors on a single place

**Comment by markov00** [comment]
closed https://github.com/elastic/elastic-charts/pull/419
