### ISSUE TITLE
[Metric] support strings

### ISSUE THREAD

**Issue by andrewctate** [elastic/elastic-charts#1801]
**Is your feature request related to a problem? Please describe.**
We would like to support string values in the Lens metric visualization in Kibana. One use case is displaying the last value of a server status field: "up" or "down."

**Describe the solution you'd like**
The metric should accept a string value as well as a numeric value for the primary metric. Since a non-numeric value doesn't make sense in the context of a progress bar or a trend line, this probably means a new type of metric datum interface that can accept a string value, while the others maintain the numeric constraint.

**Describe alternatives you've considered**
I don't see any alternative.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/137756

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
cc @gvnmagni could you check what does this means in terms of font-size/available space/text wrapping?

**Comment by gvnmagni** [comment]
The component was initially designed to allow, when at its width minimum size, a number with up to 7 chars (0000.000) without any problem. Since we got rid of the width minimum and we accept that the value might be cut when too long it seems that we could also accept text strings without having to be worried about length.

We just have to be aware that we are relying on the user "common sense" to enlarge the metric panel (once in a dashboard) to avoid cutting texts.

**Comment by markov00** [comment]
@gvnmagni Do you think we should keed the same font size for text? Do we need to truncate the text or just make it overflow the chart?

**Comment by gvnmagni** [comment]
I would keep the same font-size, yes, and truncating seems a good idea so let's try that! Thank you!
