### ISSUE TITLE
Don't skip eslint step on VRT screenshot changes

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1823]
If you push a commit with some linting errors and you immediately after pushing you also ask to update the VRTs, the eslint step is skipped (because it checks for changes in TS files) and the eslint error will never been catch and will propagate to master.

This situation could also happen every time I submit a "safe" commit (with changes to a file that is correctly linted) but I previously changed and committed a different file with some linting errors.

The CI eslint only checks file changes from the commit that runs the CI, but from the branch changes.

See for example this PR https://github.com/elastic/elastic-charts/pull/1819

Two way to solve:
- always run eslint across the repo
- run eslint to the changed file from the beginning of the branch

cc @nickofthyme

**Comment by nickofthyme** [comment]
I'll take a look, but the file diffs are determined on the entire pull request, see request below. In any case I'll take a look and see what's going on.

https://github.com/elastic/elastic-charts/blob/38642e3944ed0b1d4b91fa195a33aa14448df6e8/.buildkite/utils/github.ts#L418-L434

**Comment by nickofthyme** [comment]
@markov00 upon further review, this was happening because the PR checks where running...

```bash
NODE_ENV=production eslint --quiet --ext .tsx,.ts,.js
```

And the `main` branch would run...

```
NODE_ENV=production eslint --quiet --ext .tsx,.ts,.js .
```

Notice the `.` at the end of the second command telling `eslint` to run against all files. The linting step is designed to run only against the changed files, when no major config changes are present.

https://github.com/elastic/elastic-charts/blob/839a55cb0b29ea1b6720a38c5d0b9670facfe1e9/.buildkite/scripts/steps/eslint.ts#L44-L46

But the `input` of `filesToLint` was **NOT** being passed to the command as I expected thus running `eslint` against no files.

> I don't think there are any issues related to the commit being used as we originally surmised, but we should keep an eye on this in the future just in case.
