### ISSUE TITLE
Custom tooltip label in gauge/goal/bulletgraph

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1845]
**Is your feature request related to a problem? Please describe.**
The current label used in the gauge/goal/bullet graph is hard coded with the value `Actual`.
This doesn't follow the other chart behaviors and needs to be configurable.

**Describe the solution you'd like**
Using the `id`, or the `name` or one of the other available label in the configuration

**Describe alternatives you've considered**
Don't show a label is also an alternative, all the information are anyway already available on the screen.

**Comment by nickofthyme** [comment]
@gvnmagni One other consideration related to this is what are your thoughts on having a floating line where the user is hovering with a subdued line similar to the target line? Then in the tooltip, show this hovered value.

The tooltip screenshots above are IMHO useless, just duplciating information that is already visible.

**Comment by gvnmagni** [comment]
You are absolutely on point, I agree with you these tooltips are useless and this would be only a temporary fix in order to, at least, include the right information within that.

It is a very interesting idea to include a floating line, we should definitely consider it. I am also asking myself what are the users trying to do here when they interact with the chart, what kind of information are they looking for
