### ISSUE TITLE
Flamegraph: Add fullscreen mode

### ISSUE THREAD

**Issue by rockdaboot** [elastic/elastic-charts#1854]
**Is your feature request related to a problem? Please describe.**
To fully focus on working with the flamegraph (e.g. in Universal Profiling) a fullscreen mode for the flamegraph would be really nice to have.

**Describe the solution you'd like**
Below the flamegraph is the search panel, history etc. There, I'd like to see a fullscreen icon/image (not sure whether and which key binding makes sense here).

When in fullscreen mode, collapse icon is shown instead of the fullscreen icon.
Pressing that get the user back to the previous / normal view.

**Checklist**

- [x] this request is checked against already exist requests

**Comment by christos68k** [comment]
This is something I would also find really useful as I frequently work on laptop screens (I also think the feature is useful regardless of screen size). I did chat with @monfera about it, a few months ago,  though I no longer remember the technical details 😅

**Comment by monfera** [comment]
The chart library is pretty agnostic wrt. to the placement and size of the chart, so I think that controlling the actual full screen-ness would be best done by the call site. A chart can be of an arbitrary size (though it has a rendering perf impact). The chart library does not provide full screen or even chart resizing. But the call site is free to rerender at a dimension of its choosing. This also leaves control on the call site, as a full screen Kibana page may or nay not still need to feature certain UI elements. @gvnmagni or someone else in Design may be aware of guidance on full screen views.

So, if I understand, the only thing `elastic-charts` should provide is a button on the bottom row for maximize/restore. It is a bit non-idiomatic to provide a button of a specific style and glyph with no associated functionality other than the execution of a callback provided by the call site, but it'd work for the time being, and easier to do than letting the call site insert arbitrary affordances into the bottom control row or elsewhere (a floating control would already be doable as is, because in that case there's not much to align with). CC @markov00

**Comment by markov00** [comment]
Agree with Robert here, I'm pretty sure Kibana already have some affordances to rerender part of the screen in full-screen mode, as it's done in EUI images for example https://eui.elastic.co/#/display/image#click-an-image-for-a-fullscreen-version
Also please note that the buttons on the bottom side of the flamegraph are currently only available in this alpha version. When moving it to GA those buttons are required to be rendered outside elastic-charts to be compatible/aligned with EUI and the rest of the interface, so putting an additional "custom" button here is not a valid option.

I will close this issue as it should be implemented by the call site and not within our library

**Comment by markov00** [comment]
> The images do not become fullscreen images.

Depends on how you define "full screen" :
- the EUI link I've provided shows the ability to have a full-window size image (OS menus/browser menu/url will remain available). The same thing happens in Kibana Dashboard when you click the fullscreen button
<img width="272" alt="Screenshot 2022-11-04 at 09 50 22" src="https://user-images.githubusercontent.com/1421091/199931844-88556317-dd07-40de-8ffc-4267eefda9d6.png">

- if you want the full-screen effect of a video player, then you should implement that via JS on your local page.

In both cases, providing such feature as part of the charting library is not something we want to consider because:
- on your fullscreen experience you may want other UI elements that are not part of the flamegraph
- the flamegraph today already fills the entire space of its parent, so making it adapt to the entire window page and put it on fullscreen mode (ala video player) is a relatively simple developer task that should be handled by the application consuming the chart and not the chart itself.

**Comment by rockdaboot** [comment]
Thanks for the clarification @markov00 !

**Comment by nickofthyme** [comment]
I asked the EUI team if they have a full screen type component and it sounds like that's a not but you could build it with existing components. The `EuiPageTemple` has a full screen option but not sure that is what your are looking for, see [docs](https://eui.elastic.co/#/templates/page-template/examples). I think a better example is their `allowFullScreen ` option on `EuiImage`, see [docs](https://eui.elastic.co/#/display/image#click-an-image-for-a-fullscreen-version).

![Screen Recording 2022-11-04 at 11 30 45 AM](https://user-images.githubusercontent.com/19007109/200049592-eea94b75-3fcf-407e-8ce5-10bfba75c3e4.gif)


### Slack Convo

<img width="493" alt="image" src="https://user-images.githubusercontent.com/19007109/200048472-39bf00d5-b4af-4a28-8238-c96ca20f14ef.png">

Could be worth opening a feature request in EUI for them to create and export such a component.
