### ISSUE TITLE
[Pie] Hover shadow is shifted by slice's angle on Safari

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1937]
**Describe the issue**

Just had this weird issue in Lens with Safari while testing:

<img width="638" alt="Screenshot 2023-01-18 at 18 09 55" src="https://user-images.githubusercontent.com/924948/213248662-d7004485-ee9a-4c6d-943d-849d58b00347.png">

Safari Version 16.2 (17614.3.7.1.7, 17614)

To reproduce:
* Assign a boolean field as "Slice by" dimension
* Assign a `count by Record` as metric
* move the cursor on the pie chart

**Comment by markov00** [comment]
https://user-images.githubusercontent.com/1421091/215749583-93714856-a91a-47bf-aa5c-5b69684a2aa4.mov


Looks really like a bad SVG rendering in Safari. I can see if this can be fixed by rounding a bit the numbers in the path, but is it strange the two SVG looks the same at the beginning (with the bad rendering) and after it renders correctly:

<img width="823" alt="Screenshot 2023-01-31 at 12 34 02" src="https://user-images.githubusercontent.com/1421091/215749678-8693dfd2-c4ab-41b0-ba40-cf9d02f47319.png">, b
<img width="802" alt="Screenshot 2023-01-31 at 12 34 13" src="https://user-images.githubusercontent.com/1421091/215749675-8f936375-77f1-4eef-98c0-733b66639e77.png">

**Comment by markov00** [comment]
I also noticed an even weird behavior: it seems that my mouse act as a eraser in "semi-transparent" highlighter path

https://user-images.githubusercontent.com/1421091/215845609-60900b6e-16ae-4b42-8d53-f44f4360ac25.mov

**Comment by markov00** [comment]
> If it's only bad in the beginning maybe we could try initially rendering the svg twice.

can work, but I prefer not pollute our code with strategies to fix browser rendering bugs. We already have some of them in place unfortunately

**Comment by markov00** [comment]
I don't see a simple way to test older safari versions to check which version introduced that bug. I can check with a virtual machine but feels like a very minor problem to me

**Comment by dej611** [comment]
TBH I do not expect a fix on the library side here, both because it's such a minor thing and also because it's very specific to some versions of Safari. The aim of the issue was mostly to document and acknowledge it.
A won't fix would be ok on our side.
