### ISSUE TITLE
Usage without moment-timezone?

### ISSUE THREAD

**Issue by graup** [elastic/elastic-charts#2023]
Currently, moment-timezone is a [required peer dependency](https://github.com/elastic/elastic-charts/wiki/Consuming-@elastic-charts#using-elastic-charts-in-a-standalone-project). For various reasons, the use of moment has been [deprecated](https://github.com/you-dont-need/You-Dont-Need-Momentjs) for a while now. Moment-timezone is a particularly heavy dependency, adding 750kb to our bundle, even though it's not needed for anything. Is there any way we could make @elastic/charts work without moment-timezone? We're not using charts with any timezone features.

Is there any workaround for this?

**Comment by markov00** [comment]
Hi @graup, unfortunately, there is no simple workaround for this. 
The library is not tree shakable yet and we rely on moment and moment-timezone for time scale purposes (this library is mostly used for Elastic Kibana that internally uses moment and moment-timezone so that's why is a peer dependency and for us, this doesn't weight too much, sorry about that).

What I can suggest is to configure your bundler to alias the `moment-timezone` to its minimal version (called `no data`) which is very small and doesn't contain any timezone data.(see here https://momentjs.com/timezone and it should be available in `moment-timezone/builds/moment-timezone.min.js`) 

We have on our long-term roadmap the idea to split the library into smaller packages and this will also help reduce the bundle size depending on the used components, but there is no ETA for that at the moment.

**Comment by graup** [comment]
@markov00 Thank you, that helps!

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
