### ISSUE TITLE
[tooltip] Reconsider tooltip min-width and label truncations

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#2048]
**Is your feature request related to a problem? Please describe.**
There are valid cases where longer labels are required to be displayed in their entirety.
Some of these cases are:
- You can quickly understand from the structure of the label if the value refers to some sort of subcategory or not, for example when showing hierarchical path names like `root.package.app.service.version` 
- The right-hand side of the label is more important than the left-hand side

![image](https://github.com/elastic/elastic-charts/assets/1421091/79aca4b6-e311-4b05-bb82-463e88027baf)

**Describe the solution you'd like**
The ideal path is to be always able to visualize the entire label on the tooltip but, as always, it depends on the length of it.
We can't represent a label that is as long as the current screen width (it will occlude too much in the current view), but is also true that we cannot limit too much the width and always truncate the label.
A trade-off should be considered.
We should also consider its effects on the legend (longer label on legend will shrink the chart)

**Describe alternatives you've considered**
The multi-line wrapping was already considered in the design but could increase the height of the tooltip too much depending on the number of lines to wrap every single text.  The design idea was to wrap the text at a max 300px width.
<img width="429" alt="Screenshot 2023-05-23 at 11 14 21" src="https://github.com/elastic/elastic-charts/assets/1421091/c9cfd500-70ec-42f4-860d-c5eff39f5d08">

The beginning/middle truncation of text is an alternative option, but doesn't fully cover the extent of the problem and is a custom solution (we need to compute that manually because this type of text truncation is not available in HTML out of the box)

**Additional context**
This and other similar situations are examples of the need for a full extent tooltip width or a tooltip with a different truncation.
![](https://files.slack.com/files-pri/T0CUZ52US-F0593CKM57W/image.png)

cc @gvnmagni

**Comment by timductive** [comment]
Some more examples of where this is a problem.
![image](https://github.com/elastic/elastic-charts/assets/1280964/9a75bd93-6bcc-43ae-8897-4a46104a36d4)
![image_720](https://github.com/elastic/elastic-charts/assets/1280964/5185e60e-c084-4ff1-bf65-569760175a55)

**Comment by gvnmagni** [comment]
After a few conversations we decided that the optimal solution would be to provide these series of solution to our users.

1. We should offer different ways of truncation that could be customized according to need. Users would be able to pick which option they prefer between `begin`, `middle` and `end`
2. If no truncation is desired, tooltips could enlarge up until 500px of width and then break string into multiple lines

The following image shows these options in place. If there is anything that we missed please feel free to reach out so that we can include all we need in this update 😊

![Frame 151](https://github.com/elastic/elastic-charts/assets/18484576/4fd1367c-fbc4-4b14-812e-00bb0a71ea4d)

**Comment by teresaalvarezsoler** [comment]
hey @gvnmagni @markov00 we are looking to implement this with @mbondyra. Instead of making it configurable, I think a better solution will be to make it adjustable depending on the content: 

When there are long values we could provide the solutions mentioned above:
1. Auto-expand tooltip width up to 500px
2. Multi-line up to say 2-3 lines and middle truncate afterwards 
3. Auto-expand tooltip height up to xxx px (it seems there is still space even in small screens) <img width="1431" alt="image" src="https://github.com/elastic/elastic-charts/assets/99645649/da53ed2f-d9ca-420c-abc4-f49e78aa0b40">



Btw, why when users right click do we make the tooltip shorter and narrower? Can we keep the original size? <img width="620" alt="image" src="https://github.com/elastic/elastic-charts/assets/99645649/82e745a8-3fb3-4a10-9b3e-3baf530781e0">

**Comment by mbondyra** [comment]
@nickofthyme @markov00 this issue has been closed with my PR 🔝 but I am not sure if it should be as we were exploring different routes? Just asking to give it visibility.

**Comment by nickofthyme** [comment]
I think you were correct in closing this. I think we just open up a separate issue for addressing the label truncations described in https://github.com/elastic/elastic-charts/issues/2048#issuecomment-1692955024.
