### ISSUE TITLE
Charts tooltip - aesthetic details for selected series (checkmark and padding)

### ISSUE THREAD

**Issue by gvnmagni** [elastic/elastic-charts#2083]
**Describe the issue**
Within the charts tooltip, the checkmark icon that appears once a series is selected has no margins and therefore looks cluttered. Due to the same issue, the series label has no additional padding while it should be slightly shifted to the right

**Current behaviour**
<img width="249" alt="Screenshot 2023-06-29 at 17 09 04" src="https://github.com/elastic/elastic-charts/assets/18484576/71c8ef88-bf69-4dc2-aecb-060b970df32a">

**Expected behaviour**
<img width="307" alt="Screenshot 2023-06-29 at 17 12 34" src="https://github.com/elastic/elastic-charts/assets/18484576/9d4bf045-6dc0-4a19-a3fa-84aeb9a3efcc">

**Comment by nickofthyme** [comment]
I think the idea behind this style was to avoid shifting the labels. The tooltip is sized according to the labels and we'd need to account for this shift to prevent unwanted truncation of labels.

Also this interaction now deviates from the strict table structure, with this new approach the column widths are now potentially dependent on another column (the color/selection column and the right adjacent column) and potentially different across rows.

> This width shift could also affect our composable tooltip components with the selection column, but likely fixable

Since we are structuring the tooltip **"table"** as just `div`s with table `roles`, this styling change is not too bad, technically speaking.

I opened up a quick POC that seems to work fine with the desired change, see #2084.

<p align="center">
  <img style width="340" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/b5463baa-9651-4882-aa7f-e0e47f128b8c">
</p>

> Note: If you are looking to change the check mark we are currently using `✓` ([U+2713](https://www.compart.com/en/unicode/U+2713)) directly, as opposed to some icon. Changing this to a non-Unicode Character may be outside of this scope of these changes.
