### ISSUE TITLE
[Metric] allow array of values

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#2111]
Add the possibility to render an array of values in a concatenated way.

When passing an array of values a bar can't be rendered and the background color could only have a categorical meaning because is not possible to link a single color to a set of values.

**Screenshots (if relevant):**

This is how the legacy metric will render concatenated strings:

<img width="524" alt="Screenshot 2023-06-28 at 2 44 16 PM" src="https://github.com/elastic/kibana/assets/315764/8c30d7f3-c43a-420e-9666-930c7deaa8d8">

**Kibana cross issue**
https://github.com/elastic/kibana/issues/160815

**Comment by gvnmagni** [comment]
What do you all think about using a lighter font-weight for characters that are not part of values, as we can see in the left option where brackets and commas are in regular font weight instead of bold

<img width="1514" alt="Screenshot 2024-04-09 at 11 03 59" src="https://github.com/elastic/elastic-charts/assets/18484576/a6d49be1-18ca-4f11-8bf1-cb5ec8968f7e">
