### ISSUE TITLE
[Metric] Opacity is ignored when passed as RGBA or HEX string

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#2183]
**Describe the issue**

<img width="1218" alt="Screenshot 2023-09-29 at 14 55 01" src="https://github.com/elastic/elastic-charts/assets/924948/84de4fce-2244-430d-b27f-1f5a53213e9f">

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/167636

**Comment by nickofthyme** [comment]
This is due to the contrast logic, it's hard to accurately determine color contrast when an alpha values is present.

I think in the short-term we just disable the [`alpha` assignment](https://eui.elastic.co/#/forms/color-selection#alpha-channel-opacity-selection) in the eui color picker, if practicable in lens, for assigning metric color.

I believe we had a similar issue with the partition chart slices a while back. Now I we just blend the foreground color with the background color to run contrast logic.

Notice in [here](https://codesandbox.io/s/vibrant-water-xhsff2?file=/src/App.tsx:217-997) it accurately chooses the text color and applies the opacity.

**Comment by dej611** [comment]
> I believe we had a similar issue with the partition chart slices a while back. Now I we just blend the foreground color with the background color to run contrast logic.

Wouldn't be possible to apply the same logic in there as well?
I think such logic should be commonly shared across all chart types.

Disabling the opacity in Lens may not be desiderable, as it breaks the consistency of the palette interface across chart types.

**Comment by nickofthyme** [comment]
> Wouldn't be possible to apply the same logic in there as well?

Yeah totally, I think that is the best solution here I don't think it will be too difficult.

> Disabling the opacity in Lens may not be desiderable, as it breaks the consistency of the palette interface across chart types.

Ah gotcha, then just disregard this idea. 👍🏼
