### ISSUE TITLE
Individual tooltip formatters within a series

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#241]
**Is your feature request related to a problem? Please describe.**
As a series can have multiple y accessors, it can contain multiple data points for the same x accessor value. To format the tooltips, currently the tick formatter of the axis is used. There are situations in which it would make sense to have different formatters for the tooltip values of the individual series (e.g. because in Kibana formatters can be attached to a field which could result in two y values on the same axis with two different formatters)

**Describe the solution you'd like**
Not 100% sure about the api, but there could be a prop on the series to configure the tooltip formatters in greater detail:
```jsx
<LineSeries {...props} tooltipFormatters={{ yAccessor1: formatter1, yAccessor2: formatter2 }} />
```

If a user wants to specify just one formatter for the tooltip values which differentiates from the tick formatter, something like this could also be provided:

```jsx
<LineSeries {...props} tooltipFormatter={formatter} />
```

The specifity priority should probably be default formatter -> axis tick formatter -> single series tooltip formatter -> y-accessor specific tooltip formatter.
 

**Describe alternatives you've considered**
A current workaround is to have a separate hidden axis for each series, but to do so you have to harmonize the domains of each axis by basically doing what elastic-charts is doing internally:
-if you have all negative values and `yScaleToExtent=false` than the min domain is 0 and the max domain is the max negative value
-if you have all negative values and `yScaleToExtent=true` than the min domain is the min negative and the max domain is the max negative value
- if you have half negative and half positive values, than the min Domain is the max negative, and the max domain is the max positive

**Additional context**
-

**Kibana Cross Issues**

**Checklist**

- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Copying the same reply used in [kibana#112141](https://github.com/elastic/kibana/issues/112141#issuecomment-1070808796)

@ghudgins @flash1293 @dej611 I have reviewed this issue with @gvnmagni and we don't agree on that request because:
- each Y-axis drives the data format of what is represented along that axis. There can be a variation in the tooltip, like for example increasing the precision or including an extended unit name, but using different formatting for two different series on the same Y-axis is a bad practice. Values on the same Y-axis should be compared easily and should represent the same unit and metric.
- If you have 2 Y-axis, you can have different formatters, one for each Y-axis with a different unit, multipliers, etc. But you always have to consider the previous point: the same tuple of formatters should be used within the tooltip on each associated series (with the extent of improving the data precision).
- having a tooltip with 3 series using 3 different formattings should be avoided.

To summarize:
- a `y-axis` can use only **1** value formatter
- Each `metric` associated with a `y-axis` will **inherit** the `y-axis` formatter.
- The inherited formatter can be tweaked, at the tooltip level, to increase its precision (from 0 decimal on the axis to 2 del on the tooltip) or extend the unit (kB -> kilobyte).
- Two `metrics`, associated with the same `y-axis`, will **inherit** the same formatter on the tooltip.

A completely different discussion is if you want to introduce more information in the tooltip related to the current data point (like for example showing some correlated data value, or some contextual information). In this case, a custom tooltip needs to be delivered explaining clearly what each value is and why we are showing them.

If you disagree, please reopen this issue
