### ISSUE TITLE
package.json "engine" is too restrictive

### ISSUE THREAD

**Issue by chandlerprall** [elastic/elastic-charts#359]
The `node` version in the package.json's `engines` field is too restrictive to include `elastic-charts` in other projects. For example, EUI's CI breaks when trying to add elastic charts as we are not on that exact `10.15.2` node version. Even if we were to update and track this version requirement, we'd be forcing all consumers of EUI to use that specific node version, even in non-Kibana use cases.

**Comment by markov00** [comment]
Hey @chandlerprall 
I think we need to change the .nvmrc config instead. 
Quoting https://docs.npmjs.com/files/package.json#engines 
> Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

So I think it's our `.nvmrc` that create issues with the CI

**Comment by markov00** [comment]
...and rethinking about my last comment, it's also more strange because the `.nvmrc` is not inside the distributed package, but only on the repo

**Comment by markov00** [comment]
ok so actually that `note` is only for `npm` and doesn't apply to `yarn`.
On yarn the that thing is only applied when passing `--ignore-engines`
Let me check to what version we can downgrade to satisfy our packages and I will update the library

**Comment by markov00** [comment]
So I've investigated a bit more the issue, here my findings:
- as part of our devDependency we are using `commitizen` that has a strict engine require of node >=10 https://github.com/commitizen/cz-cli
- when you execute `yarn` on the CI, `yarn` download the linked dependency of a direct dependency (in your case the dependencies of `@elastic/charts`) using `yarn --production`
- the issue is: `yarn` resolved the devDependencies to create deterministic build between prod and dev builds https://github.com/yarnpkg/yarn/issues/3630 
- this goes in hand with this issue: https://github.com/yarnpkg/yarn/issues/5796 where `yarn --production` does the engines check on dev dependency

So the problem now is: it doesn't  matter if we remove the `engines` configuration on the release `package.json`, we also have to get remove of the `commitizen` dependency at least. This, btw, will not completely create a deterministic build because there can maybe be shared dependencies between the existing packages.

Maybe the solution is completely remove the `commitizen` CLI from the package. @nickofthyme what do you think?

**Comment by jbudz** [comment]
Hmm - [related](https://github.com/elastic/elastic-charts/pull/361), I'm trying to upgrade kibana's node version now and it's being blocked on this.  It looks like CI is installing kibana w/ a circular depdency on node version mismathes now :).  LMK if I can help

**Comment by jbudz** [comment]
Maybe engines in this repo could indice what versions of node this package supports, so it would be >=10 or something?

**Comment by markov00** [comment]
Hey @chandlerprall we changed the `engines` to a less restrictive version >=10.
We cannot easily go down to version 8 because was required by `commitizen`. We need to keep the commitizen adapter in the package because it's required, but this will pull in the commitizen lib with the node >=10 requirement

**Comment by chandlerprall** [comment]
@markov00 was there no luck/success with publishing the package with no `engines` field?

**Comment by nickofthyme** [comment]
Just to update per slack conversation

- Keeping `engines` at `node@10` for the meantime
- Long term solution switch to yarn workspace and remove `engines` altogether
