### ISSUE TITLE
Use all Kibana timezones in the timeZone prop

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#428]
**Is your feature request related to a problem? Please describe.**
the `timeZone` prop use only IANA time zones identifiers.
Kibana use instead a mix of IANA and other time zone indentifiers.

**Describe the solution you'd like**
We should support all time zones available in kibana

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Kibana Cross Issues**
n/a

**Checklist**

- [x] this request is checked against already exist requests
- ~[ ] every related Kibana issue is listed under `Kibana Cross Issues` list~
- ~[ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present~

**Comment by markov00** [comment]
Luxon relies on `Intl.DateTimeFormat` to handle date formatting.
The timeZones recognized names depends on each browser implementation, IE for example doesn't have the Zone names (it will only recognize the UTC + the local one)


Right now we cannot fix it in Kibana adding a polyfill: https://github.com/formatjs/date-time-format-timezone: Unfortunately this doesn't fix completely the issue, see https://github.com/formatjs/date-time-format-timezone/issues/36


The only fix I see is replace Luxon with Momentjs. This means: adding a big and mutable library to the project.

**Comment by nickofthyme** [comment]
@markov00 based on some back and forth testing the different approaches. Below are my thoughts.

## Global `KbnTimeZone` component

I think this is still a viable approach but it is more complicated than I originally thought.

The timezone is able to be set for each series, which would introduce two sources of truth. If this is the approach we want to take we should remove the `timeZone` props in favor of the `TimeZone` component to handle all timezones on a global level.

## `moment-timezone`

This seems to be the quickest and most compatible solution. Looking at the missing timezones from `Intl` and `spacetime` there are still a lot missing and the tz mapping is not helpful. Whereas all the kibana timezones are supported by `moment`.

## `spacetime`

This would be a similar solution to luxon but it is a slightly larger bundle size. I'm thinking if we are just adding a library to facilitate time zones why not use a peer dependency over a separate library.

## `Intl` polyfill with `luxon`

This is a promising solution however would still be missing dozens on timezones.

I couldn't reproduce the issue you saw in Chrome with the polyfill. However, I think we could just run a simple test in the `scale_continues` file where we call `Intl` to see if it works, otherwise load it.

```ts
try {
  console.log('testing poly');
  // Some way to test if the polyfill/Intl works
  // I thought we could just check if IE then load it, but this seams more pragmatic.
  new Intl.DateTimeFormat('en', {
    timeZone: 'America/Los_Angeles',
    timeZoneName: 'long',
  }).format(new Date());
} catch (error) {
  console.log('loading poly');
  require('date-time-format-timezone');
}
```
> This would cause a slight delay when loading the first chart, if it's required.

The drawbacks of this are that there are still unsupported time zones from the Kibana list.

## Summary of test results

<details><summary>Missing timezones in Chrome</summary>
<br/>

| Time zone | spacetime | Intl |
|:-:|:-:|:-:|
|  America/Fort_Nelson  |  :x:  |  :white_check_mark:  |
|  Asia/Famagusta  |  :x:  |  :white_check_mark:  |
|  Asia/Qostanay  |  :x:  |  :white_check_mark:  |
|  Asia/Yangon  |  :x:  |  :white_check_mark:  |
|  CET  |  :x:  |  :x:  |
|  Cuba  |  :x:  |  :white_check_mark:  |
|  EET  |  :x:  |  :x:  |
|  EST  |  :x:  |  :x:  |
|  Egypt  |  :x:  |  :white_check_mark:  |
|  Eire  |  :x:  |  :white_check_mark:  |
|  Etc/UCT  |  :x:  |  :x:  |
|  GB  |  :x:  |  :white_check_mark:  |
|  GB-Eire  |  :x:  |  :white_check_mark:  |
|  GMT+0  |  :white_check_mark:  |  :x:  |
|  GMT-0  |  :white_check_mark:  |  :x:  |
|  GMT0  |  :white_check_mark:  |  :x:  |
|  HST  |  :x:  |  :x:  |
|  Hongkong  |  :x:  |  :white_check_mark:  |
|  Iceland  |  :x:  |  :white_check_mark:  |
|  Iran  |  :x:  |  :white_check_mark:  |
|  Israel  |  :x:  |  :white_check_mark:  |
|  Japan  |  :x:  |  :white_check_mark:  |
|  Libya  |  :x:  |  :white_check_mark:  |
|  MET  |  :x:  |  :x:  |
|  MST  |  :x:  |  :x:  |
|  NZ  |  :x:  |  :white_check_mark:  |
|  NZ-CHAT  |  :x:  |  :white_check_mark:  |
|  Navajo  |  :x:  |  :white_check_mark:  |
|  PRC  |  :x:  |  :white_check_mark:  |
|  Poland  |  :x:  |  :white_check_mark:  |
|  Portugal  |  :x:  |  :white_check_mark:  |
|  ROC  |  :x:  |  :white_check_mark:  |
|  ROK  |  :x:  |  :white_check_mark:  |
|  Turkey  |  :x:  |  :white_check_mark:  |
|  UCT  |  :x:  |  :x:  |
|  US/Alaska  |  :x:  |  :white_check_mark:  |
|  US/Aleutian  |  :x:  |  :white_check_mark:  |
|  US/Arizona  |  :x:  |  :white_check_mark:  |
|  US/Central  |  :x:  |  :white_check_mark:  |
|  US/East-Indiana  |  :x:  |  :white_check_mark:  |
|  US/Eastern  |  :x:  |  :white_check_mark:  |
|  US/Hawaii  |  :x:  |  :white_check_mark:  |
|  US/Indiana-Starke  |  :x:  |  :white_check_mark:  |
|  US/Michigan  |  :x:  |  :white_check_mark:  |
|  US/Mountain  |  :x:  |  :white_check_mark:  |
|  US/Pacific  |  :x:  |  :white_check_mark:  |
|  US/Pacific-New  |  :x:  |  :white_check_mark:  |
|  US/Samoa  |  :x:  |  :white_check_mark:  |
|  W-SU  |  :x:  |  :white_check_mark:  |
|  WET  |  :x:  |  :x:  |
</details>

<details><summary>Missing timezones in IE</summary>
<br/>

| Time zone | spacetime | Intl |
|:-:|:-:|:-:|
|  America/Punta_Arenas  |  :question:  |  :white_check_mark:  |
|  Asia/Atyrau  |  :question:  |  :white_check_mark:  |
|  Asia/Barnaul  |  :question:  |  :white_check_mark:  |
|  Asia/Famagusta  |  :question:  |  :white_check_mark:  |
|  Asia/Qostanay  |  :question:  |  :white_check_mark:  |
|  Asia/Tomsk  |  :question:  |  :white_check_mark:  |
|  CET  |  :question:  |  :white_check_mark:  |
|  EET  |  :question:  |  :white_check_mark:  |
|  EST  |  :question:  |  :white_check_mark:  |
|  Etc/GMT  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+0  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+1  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+10  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+11  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+12  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+3  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+4  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+5  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+6  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+7  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+8  |  :question:  |  :white_check_mark:  |
|  Etc/GMT+9  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-0  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-1  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-13  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-14  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-2  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-3  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-4  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-5  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-6  |  :question:  |  :white_check_mark:  |
|  Etc/GMT-8  |  :question:  |  :white_check_mark:  |
|  Etc/GMT0  |  :question:  |  :white_check_mark:  |
|  Etc/Greenwich  |  :question:  |  :white_check_mark:  |
|  Etc/UCT  |  :question:  |  :white_check_mark:  |
|  Etc/UTC  |  :question:  |  :white_check_mark:  |
|  Etc/Universal  |  :question:  |  :white_check_mark:  |
|  Etc/Zulu  |  :question:  |  :white_check_mark:  |
|  Europe/Kirov  |  :question:  |  :white_check_mark:  |
|  Europe/Saratov  |  :question:  |  :white_check_mark:  |
|  GMT  |  :question:  |  :white_check_mark:  |
|  GMT+0  |  :question:  |  :white_check_mark:  |
|  GMT-0  |  :question:  |  :white_check_mark:  |
|  GMT0  |  :question:  |  :white_check_mark:  |
|  Greenwich  |  :question:  |  :white_check_mark:  |
|  HST  |  :question:  |  :white_check_mark:  |
|  MET  |  :question:  |  :white_check_mark:  |
|  MST  |  :question:  |  :white_check_mark:  |
|  UCT  |  :question:  |  :white_check_mark:  |
|  Universal  |  :question:  |  :white_check_mark:  |
|  WET  |  :question:  |  :white_check_mark:  |
|  Zulu  |  :question:  |  :white_check_mark:  |

> Spacetime was giving me a syntax error in IE that was not easy to debug

</details>

<details><summary>Missing timezones in Firefox</summary>
<br/>

| Time zone | spacetime | Intl |
|:-:|:-:|:-:|
|  America/Fort_Nelson  |  :x:  |  :white_check_mark:  |
|  Asia/Famagusta  |  :x:  |  :white_check_mark:  |
|  Asia/Qostanay  |  :x:  |  :white_check_mark:  |
|  Asia/Yangon  |  :x:  |  :white_check_mark:  |
|  CET  |  :x:  |  :white_check_mark:  |
|  Cuba  |  :x:  |  :white_check_mark:  |
|  EET  |  :x:  |  :white_check_mark:  |
|  EST  |  :x:  |  :white_check_mark:  |
|  Egypt  |  :x:  |  :white_check_mark:  |
|  Eire  |  :x:  |  :white_check_mark:  |
|  Etc/UCT  |  :x:  |  :white_check_mark:  |
|  GB  |  :x:  |  :white_check_mark:  |
|  GB-Eire  |  :x:  |  :white_check_mark:  |
|  HST  |  :x:  |  :white_check_mark:  |
|  Hongkong  |  :x:  |  :white_check_mark:  |
|  Iceland  |  :x:  |  :white_check_mark:  |
|  Iran  |  :x:  |  :white_check_mark:  |
|  Israel  |  :x:  |  :white_check_mark:  |
|  Japan  |  :x:  |  :white_check_mark:  |
|  Libya  |  :x:  |  :white_check_mark:  |
|  MET  |  :x:  |  :white_check_mark:  |
|  MST  |  :x:  |  :white_check_mark:  |
|  NZ  |  :x:  |  :white_check_mark:  |
|  NZ-CHAT  |  :x:  |  :white_check_mark:  |
|  Navajo  |  :x:  |  :white_check_mark:  |
|  PRC  |  :x:  |  :white_check_mark:  |
|  Poland  |  :x:  |  :white_check_mark:  |
|  Portugal  |  :x:  |  :white_check_mark:  |
|  ROC  |  :x:  |  :white_check_mark:  |
|  ROK  |  :x:  |  :white_check_mark:  |
|  Turkey  |  :x:  |  :white_check_mark:  |
|  UCT  |  :x:  |  :white_check_mark:  |
|  US/Alaska  |  :x:  |  :white_check_mark:  |
|  US/Aleutian  |  :x:  |  :white_check_mark:  |
|  US/Arizona  |  :x:  |  :white_check_mark:  |
|  US/Central  |  :x:  |  :white_check_mark:  |
|  US/East-Indiana  |  :x:  |  :white_check_mark:  |
|  US/Eastern  |  :x:  |  :white_check_mark:  |
|  US/Hawaii  |  :x:  |  :white_check_mark:  |
|  US/Indiana-Starke  |  :x:  |  :white_check_mark:  |
|  US/Michigan  |  :x:  |  :white_check_mark:  |
|  US/Mountain  |  :x:  |  :white_check_mark:  |
|  US/Pacific  |  :x:  |  :white_check_mark:  |
|  US/Pacific-New  |  :x:  |  :white_check_mark:  |
|  US/Samoa  |  :x:  |  :white_check_mark:  |
|  W-SU  |  :x:  |  :white_check_mark:  |
|  WET  |  :x:  |  :white_check_mark:  |

</details>

**Comment by nickofthyme** [comment]
This is the PR I was testing with. https://github.com/elastic/elastic-charts/pull/432

Let's talk in the morning and figure out a gameplan!
