### ISSUE TITLE
Rendering bug with stacked data

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#487]
I am testing out data formats that are used in Kibana, and found this example. For this sample SQL query there is incorrect rendering.

Sample query: `SELECT geo.src, geo.dest, COUNT(*) as C GROUP BY geo.src, geo.dest ORDER BY COUNT(*) DESC LIMIT 50`

This rendering shows all the data on the legend, but does not draw any bars.

<img width="688" alt="Screenshot 2019-12-06 15 07 02" src="https://user-images.githubusercontent.com/666475/70354071-bb6feb80-183c-11ea-88d5-9e58de94faec.png">

I've created a minimal test case here for you to see the data used: https://codesandbox.io/s/async-meadow-divin

<details><summary>See the full data set</summary>
<code><pre>
const rows = [['IN', 'IN', '142'],
['IN', 'CN', '50'],
['CN', 'CN', '49'],
['CN', 'IN', '41'],
['CN', 'US', '24'],
['US', 'IN', '24'],
['IN', 'US', '22'],
['US', 'CN', '18'],
['CN', 'ID', '13'],
['ID', 'CN', '13'],
['US', 'US', '13'],
['CN', 'BR', '11'],
['JP', 'IN', '10'],
['BR', 'CN', '9'],
['BR', 'IN', '8'],
['IN', 'BD', '8'],
['IN', 'BR', '8'],
['IN', 'IR', '8'],
['IN', 'PK', '8'],
['IT', 'CN', '8'],
['CN', 'DE', '7'],
['KR', 'CN', '7'],
['MX', 'IN', '7'],
['NG', 'CN', '7'],
['US', 'ID', '7'],
['CN', 'BD', '6'],
['CN', 'MM', '6'],
['CN', 'MX', '6'],
['CN', 'NG', '6'],
['CN', 'RU', '6'],
['ES', 'IN', '6'],
['ID', 'IN', '6'],
['IN', 'ID', '6'],
['US', 'BR', '6'],
['US', 'TR', '6'],
['BD', 'CN', '5'],
['BD', 'IN', '5'],
['BR', 'US', '5'],
['CN', 'ES', '5'],
['CN', 'JP', '5'],
['EG', 'IN', '5'],
['ES', 'CN', '5'],
['ID', 'US', '5'],
['IN', 'EG', '5'],
['IN', 'JP', '5'],
['IN', 'MX', '5'],
['IN', 'NG', '5'],
['IN', 'PH', '5'],
['PK', 'CN', '5'],
['PK', 'IN', '5']];
</pre></code>
</details>

There is also some connection to this Canvas issue: https://github.com/elastic/kibana/issues/52419

**Comment by wylieconlon** [comment]
I've compared our rendering to how Vega deals with the same dataset, for reference:

<img width="504" alt="Screenshot 2019-12-06 15 48 43" src="https://user-images.githubusercontent.com/666475/70355392-02abab80-1840-11ea-84da-6c530d8979ca.png">

[Try it in the vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2KPGV50jJcgBOajZBSNq+A5CNKTZy9YiQd6EwdAQXhToYqzIsAYA2pGQAJIAcmpQCUkAjNIATAC66oFgMSmqUADCiUUArAAMORoQMaVJkA1F0gCcNXn1Zcnd0qkdgV2NAKoAykkZ0gN1kGONhWCT0-lx3bPjRRnZuYPrjc1gqQAcy0NFcQAiaQDMp5f73am3OzNz52+Hz7UrB5AAQgAlNL9F4rABSAAV5o9qqCYoCHkl2nD-kDzgsTiiFv8rkVMd8CmsEXi7tjYmiwPjOqtGhCANJJKm7WIAFURJJRvwuAFEkgB2O50ilNboClEAWQAGtD+Xd4gBxdlgMUEvbo3HKu6-P4agBsWrW4vFSX1nMN0qKptVvwVJoNjQBwztKO5Gx6ztVsQ1NMtpLWXo91I+qMDu2DLIpVupOqV5TuMfR3TjKOJUA+yeta1dSQz1N+kJzd25isThZdbpFZc93vTfsaxar1OxBYqdfOUsbzLWttbWLWEIAEp2ZvTY3dR6XW1kNABfHaQDAWADWTnY6Cs8+QSiMOjM1H830gAA9-FAAGaMZBiHROSqNPAAT0IyCc3Asu6UIUaigseCcIgfSAwDnQ9AJwYBz0va8nAye8nxfHBIAAR1YdBXGYXxGCoICQLyZxuDEN9T0gC8rxvRDUjg58nCUbhUDML9zgQEIELACDIH4NBWOcXwaDfB8MjvYDgNnEAZyAA)

**Comment by markov00** [comment]
@wylieconlon the y axis is a linear scale but in the data table the y values are strings.
We don't automatically convert them to numbers because we assume a valid dataset configured by the user. If you remap the dataset converting the y value to a number it will correctly show the stacked bar chart:
<img width="925" alt="Screenshot 2019-12-06 at 23 29 45" src="https://user-images.githubusercontent.com/1421091/70361152-db290300-1880-11ea-86fe-63cbca660f1d.png">

**Comment by wylieconlon** [comment]
Okay yes, I see that now if I convert the values to numbers they are rendered correctly. What I don't understand is- if the `linear` scale can't handle strings, why does render at all?

**Comment by markov00** [comment]
It's a d3 scale magic :D

**Comment by markov00** [comment]
Or there is something else going on in our chart that wrongly interpret the numbers here. Let me check and I will be back

**Comment by markov00** [comment]
Ok, so this has something to deal with the way we compute the stacked values.
Since we expect the y to be a number, to compute the y position of a stacked bar we sum the current value with the previous value. You can easily imagine what can happen if you "sum" two strings...
<img width="256" alt="Screenshot 2019-12-06 at 23 50 20" src="https://user-images.githubusercontent.com/1421091/70361887-6acfb100-1883-11ea-9949-f6e00dd69ba0.png">
