### ISSUE TITLE
Partition style chart (pie, treemap, etc) tooltips cause scrollbars to appear.

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#596]
**Describe the bug**
Partition style chart (pie, treemap, etc) tooltips cause scrollbars to appear.

**To Reproduce**
1. Make a treemap not in Storybook
2. Hover a treemap piece

**Expected behavior**
No scrollbars should appear

**Screenshots**
![Screen Capture on 2020-03-23 at 15-59-17](https://user-images.githubusercontent.com/549577/77359109-7acfab80-6d21-11ea-9724-5706d0ab0b18.gif)

**Comment by monfera** [comment]
Thanks for the report Caroline - @markov00 have you got a hunch on this one?

**Comment by markov00** [comment]
That is something that was already there also with the XY chart, it's visible in our storybook (see https://github.com/elastic/elastic-charts/issues/453)
Unfortunately this happens because of the css used to correctly display the tooltip. I will investigate on it a bit more to see if we can fix that behaviour changing the current tooltip  behaviour

**Comment by abdul737** [comment]
Having the same issue
