### ISSUE TITLE
Fill and link labels should look the same

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#600]
**Describe the bug**
The link labels should look exactly the same and take the same config options as the inner fill labels since they're the same data representation just on the outside vs in.

**Screenshots**
![Screen Shot on 2020-03-23 at 16:39:40](https://user-images.githubusercontent.com/549577/77361141-20384e80-6d25-11ea-8909-a9e5c529213a.png)

**Comment by monfera** [comment]
Thanks Caroline, will do!

**Comment by monfera** [comment]
Draft output of what's coming up (one missing value as Canvas2d text rendering requires measurement and per font spec positioning, much more tedious than it would be in HTML)
![image](https://user-images.githubusercontent.com/1548516/77468371-bc3d8500-6e0d-11ea-9622-8e57c8eb4dc3.png)

**Comment by monfera** [comment]
Actual code example, throwing in **_bold italic_**. 
![image](https://user-images.githubusercontent.com/1548516/77474783-ff9cf100-6e17-11ea-97df-b4b2476749f0.png)
There's a larger gap on the right hand side, because at the moment, the text measurement is slightly inaccurate, which is more noticeable with unusually long texts like here.
