### ISSUE TITLE
Band charts should show y0 value in tooltip, be treated as a single series

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#607]
I'm exploring how we will visualize bounded data in Lens, and found this issue. As seen in [this band chart](https://codesandbox.io/s/focused-field-tpjm0), the lower value is not shown in the tooltip.

<img width="497" alt="Screenshot 2020-03-25 17 46 28" src="https://user-images.githubusercontent.com/666475/77588612-991fdd80-6ec0-11ea-96d0-d358daa5738f.png">

Also, I would like to treat a band as a single series, not as a two series. It doesn't seem like it's possible to get the series name to only show up once in the legend, even using code like:

```
          y0AccessorFormat={''}
          y1AccessorFormat={''}
```

**Comment by markov00** [comment]
Thanks @wylieconlon, it's definitely something we have to fix.
We are currently showing two element in the legend because TSVB was the first using banded area chart and that was the way it was implemented there (mainly because we are showing the highlighted values directly on the legend). We can find a good option to show/hide split on the legend, by default hiding that when using categorical series like the one in the example
