### ISSUE TITLE
Treemap in infinite loop when `valueAccessor` returns zero

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#642]
This is a bug in the treemap only, not in the sunburst chart. To reproduce:

1. Modify one of the 2-layer treemap examples to sometimes return 0 in the valueAccessor function, such as `valueAccessor={(d: Datum) => Math.random() < 0.7 ? d.exportVal as number : 0}`
2. Refresh the storybook
3. You will see that the chart throws an infinite loop:

```
RangeError: Maximum call stack size exceeded
    at Function.get [Symbol.species] ()
    at Array.concat ()
    at push../src/chart_types/partition_chart/layout/utils/treemap.ts.__spread 
```

When I change the exact same chart to `partitionLayout: PartitionLayout.sunburst`, the chart renders.

**Comment by monfera** [comment]
@wylieconlon thanks for the note. Partition accessors were designed with referentially transparent functions in mind - how does this situation arise in the code? Are you using a [closure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures)) that changes the value depending on previous invocations, and is there expectation for this? 

If possible, I'd like to avoid the materialization of the accessor-mapped input as the first step, as it'd be extra code, and often, performance overhead, which is why it'd be good to see if you have a need for stateful "accessors" or there can be a pure function that reproduces the issue.

**Comment by wylieconlon** [comment]
@monfera I was reproducing this in Lens, where depending on the query results we sometimes get data with 0s in it. So yes, this is reproduceable without a random data set- you could instead change some of the sample objects in the storybook to include 0s.

**Comment by monfera** [comment]
Renaming this as more than one layer is not a prerequisite
