### ISSUE TITLE
Partition chart text should scale uniformly along sectors/rings 

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#661]
**Is your feature request related to a problem? Please describe.**
Shortest texts stand out more than longer texts in a treemap or pie chart because their fonts can take up much more space than longer texts. This can distort the represented data when the user gives a quick look without at the chart without giving some time to understand the whole picture.
Check the following examples:
<img width="448" alt="Screenshot 2020-05-04 at 10 55 06" src="https://user-images.githubusercontent.com/1421091/80950379-01ce7400-8df6-11ea-905d-c3320f29c2b4.png">

In this case, `Belgium` stands out much more than the Netherlands also if from the data it's the opposite and the difference is very small.

<img width="395" alt="Screenshot 2020-05-04 at 10 51 32" src="https://user-images.githubusercontent.com/1421091/80950743-bc5e7680-8df6-11ea-8614-050503536f4a.png">

In this other case, Asia and Europe on the second layer look much bigger than the United States one.

**Describe the solution you'd like**
I'm imaging a possible configuration option to allow scaling each font uniformly, from the biggest to the smallest. Each sector should compute its max font size depending on the computed font-size of the previous one.

**Comment by monfera** [comment]
Thanks @markov00 for writing up the issue. This has been on the radar, @VijayDoshi made this suggestion a while back too. It is a good option, and the results are more balanced text heft wise, esp. with one or two layer sunburst/treemap.

The tradeoff is reduced scaling in legibility: a single bad case (eg. narrow box, long word) can yield a small, maybe unrenderably small text for all the subsequent boxes too, even if those could otherwise be rendered. For this reason, and also, not to cause a breaking change, the current PR has `layers: [ { fillLabel: { monotonic: false } } ]` as a default; can be changed if it's important enough to cause a breaking change. Also, maybe the current logic could be augmented by still allowing the use of the smallest font size even if there was a larger value with text that didn't fit even with the smallest font size.

The logic is currently per layer. This is uncontroversial with the treemap as groove texts are bound to be small. For sunburst, it looks preferable too, because otherwise a single, small inner slice can lead to small fonts in all the outer rings. However it can still lead to cases where an outer sector has a larger font than an inner sector of lower value, eg. `Mineral fuels` vs `Machinery / North America` (can be the other way around too). Once we introduce global monotonicity, new tradeoffs of diminishing returns arise 😸 

![image](https://user-images.githubusercontent.com/1548516/82738709-1ab5af80-9d3a-11ea-90e9-f07a64233a06.png)

Treemap, also three layers, also with knobs:

![image](https://user-images.githubusercontent.com/1548516/82738851-2190f200-9d3b-11ea-945b-e55d845f8f01.png)

The current issue and PR response leaves other aspects of "text ink weight perception" unaddressed: text lengths and even the character shapes in the texts impact visual weight. Further, possible improvements might help, but again, there are diminishing returns, so prioritization would be needed:

- shortening texts with `...`
- line break with hyphenation for long fill text words
- letting the chart choose from an alternative set of text lengths as SAP does, eg. 
  - `"UK"`
  - `"United Kingdom"`
  - `"United Kingdom of Great Britain and Northern Ireland"`
