### ISSUE TITLE
In stack chart show all stacked values on tooltip

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elastic-charts#68]
Currently on stack chart when hovering on an area it only shows the values of the what the mouse is hovering on, it requires the users to be more accurate with their mouse hovering, which in busy charts can be challenging, also it is harder to compare values since you can only get a single value at each time. It will be more helpful if in stack chart you can see the values of all the stacked lines/bar/areas once hovering, either in the legend or in the tooltip (preferred) 
current (you can't tell how much exactly the blue bar is): 
![image](https://user-images.githubusercontent.com/32550316/53024472-00dd3c80-3414-11e9-8713-941f5456d7d0.png)

multiple values in tooltip:

![image](https://user-images.githubusercontent.com/32550316/53024452-f753d480-3413-11e9-96e6-7e339292a0d1.png)

**Comment by markov00** [comment]
@AlonaNadler do you see this as an enforced practice in code or something that can be selected by the user/developer?
We will add the crosshair interaction that will work exactly as you describe: for each x value it will shows the Y values of all the series in a single tooltip.
I've some concerns on enforcing and that's the reason we want to let the user/dev choose:
- it depends on the data context: you may be don't want to compare the two values and only visualize single tooltips
- you may have 10 stacked elements creating a very crowded tooltip for crosshair (specially when you are splitting your chart)
- what happens when we just cluster our bars instead of stack them? this doesn't mean that we don't want to compare the clustered bars together.

**Comment by AlonaNadler** [comment]
> * what happens when we just cluster our bars instead of stack them? this doesn't mean that we don't want to compare the clustered bars together.

The existing behavior makes sense for cluster bars, I don't think you need to change anything there.
My issue is only for stacked, It will help to see in the tooltip the line users hovering on in the first line and then the rest, you can limit it or make it scrollable

**Comment by markov00** [comment]
@AlonaNadler great, I will close this in favour of https://github.com/elastic/elastic-charts/issues/80 that will track this feature
