### ISSUE TITLE
Click interactions with moving mouse pointer are not recognised

### ISSUE THREAD

**Issue by Dosant** [elastic/elastic-charts#748]
**Describe the bug**
Looks like `onElementClick` event works only if pointer position during `mousedown` event is the same as during `mouseup` event. If mouse pointer is moved during click, then `onElementClick` interaction isn't firing. This seems to be different from native browser behaviour, where click events are still recognised if mouse pointer is moved. This difference makes clicks in elastic charts flaky when using a mouse, because start-end positions could be different when clicking while the mouse in motion. 

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/interactions--sunburst-slice-clicks
2. Mousedown in one of the slices. 
3. Slightly change pointer position, leaving the mouse in the same slice
4. Mouse up
5. See `onElementClick` didn't fire

**Expected behaviour**
`OnElementClick` interactions fires

**Version (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 83
 - Elastic Charts: 27.0.0

**Additional context**

Noticed while working in a kibana dashboard.

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.
- [ ] TODO.. didn't create issue, but it is relevant

**Checklist**
Delete any items that are not applicable to this issue.

- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by streamich** [comment]
Happens when using Apple's Magic Mouse, e.g. on fast clicking clicks are not recognized.

**Comment by markov00** [comment]
As noted by @Dosant we are not using directly the browser capabilities for click because we need to handle both dragging and click cases separately and we handle mouse events in redux.
If we detect a mouse down followed by a mouse up without a mouse move event in between we then configure this as a click, with a mouse move in between instead is a drag event for us.
What we can do is to check if the time between mouse-down and mouse-up is below a certain threshold we can consider it as a click also if there was a movement in between.
