### ISSUE TITLE
Charts appear shrunk when using long tooltip header

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#758]
I couldn't find an identical bug report, but it's possible that there is one. In Lens we are setting the tooltip headerFormatter to show the X axis value, with a code snippet like this:

```
<Settings
  tooltip={{ headerFormatter: () => 'Winnipeg / James Armstrong Richardson International Airport' }}
/>
```

The rendered result looks like this:

<img width="686" alt="Screen Shot 2020-07-21 at 5 18 06 PM" src="https://user-images.githubusercontent.com/666475/88108120-4efcef00-cb76-11ea-9e24-f1ca3ea11ee0.png">

This can be reproduced in the storybooks, so I think this is a real issue. It's not super high severity, but it's definitely noticeable.

**Comment by nickofthyme** [comment]
Thanks @wylieconlon, we'll look into it!

**Comment by markov00** [comment]
This is not because of the tooltip header has a long name, but happens when the data category contains such long names.
In fact, you see that all the tick labels are hidden because all of them overlap with each other. The chart also shrinks to accommodate "correctly" display the last label without truncations but fails in that.
It's definitely a bug and we should fix this in 3 steps:
- provide a way to truncate label text
- if hiding the overlapping labels, these labels should not be used to compute the chart size
- we should add the ability to wrap labels into multiple lines
