### ISSUE TITLE
Display orphan data points on line/area charts also if the point style is invisible

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elastic-charts#783]
I heard from Lens team this is how Elastic chart displays, so opening this issue here 
![image](https://user-images.githubusercontent.com/32550316/90155910-bacf1380-dd40-11ea-991f-176ddbd8aab1.png)

When in Lens and with sparse data the dops/points  on the chart shows empty even though once her on them they have value
The behavior doesn't make sense

**Comment by markov00** [comment]
I think this was left behind due to the closing of this issue: https://github.com/elastic/elastic-charts/issues/63
Right now, it's only possible to show orphan data points of a line/area chart only if we have the point style of that chart type set to visible.
We should be able to identify these data points and mark then as visible, independently from their current style
