### ISSUE TITLE
Enable click on the whole bucket

### ISSUE THREAD

**Issue by cauemarcondes** [elastic/elastic-charts#846]
**Is your feature request related to a problem? Please describe.**
When the difference between buckets is too big on a Bar chart, clicking on a bucket is very difficult as shown in the gif below.

![charts-bar-click](https://user-images.githubusercontent.com/55978943/95096089-21aeee80-072c-11eb-9150-9089180c8e1f.gif)

**Describe the solution you'd like**
I would like to have the whole bucket area clickable.

<img width="144" alt="Screenshot 2020-10-05 at 17 01 02" src="https://user-images.githubusercontent.com/55978943/95096349-6f2b5b80-072c-11eb-9a97-d9f613e1fa0c.png">

**Comment by formgeist** [comment]
@nickofthyme Greetings! I just wanted to raise this issue because we're quite dependent on this usability in our distribution chart in APM, and it would be great to resolve this before shipping 7.11 so we can test the clickable container. Are you still confident in shipping this for 7.11?

I put together a list of blockers and polish for the APM team here https://github.com/elastic/kibana/issues/84178 with some more context.
