### ISSUE TITLE
Allow a configurable title of the legend

### ISSUE THREAD

**Issue by timroes** [elastic/elastic-charts#862]
To make timelion in Kibana use elastic-charts we'd need to be able to have the "header"/"title" of the legend be configurable. This currently shows the active hovered time when you hover over the chart. We'd need this either built into elastic-chart, or make the title configurable, so we can build this implementation on the Kibana side:

![screenshot-20201008-100941](https://user-images.githubusercontent.com/877229/95455981-ec461300-096e-11eb-8e60-aa492ca076fb.png)

**Kibana cross issue:** https://github.com/elastic/kibana/issues/79984

**Comment by markov00** [comment]
I've taken a deeper look at Timelion and I think we can live without that feature for the following reasons:
- when moving the mouse over the chart, Timelion doesn't show the tooltip, but the legend act as a tooltip: the header is the current cursor position along the x-axis + every series current value. Our tooltip works exactly in the same way at the moment.
- keep consistency with other tools using elastic-charts: I think it's preferable to use the same tooltip all over the place, instead of having Timelion charts with a Legend-Tooltip but Lens one having Legend + Tooltip
- in a near future, the tooltip and the legend can be designed as a unique and interchangeable component, and at that point, we can have a fixed legend/tooltip like today in Timelion. I prefer to work on this together with all the legend and tooltip redesign effort #580 #615 

@timroes are you ok if we change the way Timelion legend/tooltip works and align that to the available behavior of elastic-charts? The need to render the legend within the chart will remain and we will work on that

**Comment by stratoula** [comment]
@markov00 as this legend appears on hover as the tooltip I am fine with that and I agree, let's be consistent

**Comment by markov00** [comment]
Ok good, I'm closing this ticket as we are not going to implement the requested feature. 
If required, please feel free to reopen it

**Comment by yannbolliger** [comment]
Would be awesome to have customisable legend titles.
