### ISSUE TITLE
Auto min value on log scale

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#916]
**Is your feature request related to a problem? Please describe.**
When using a log scale the min value is hard coded to `1`.

https://github.com/elastic/elastic-charts/blob/f99ba1fd91a6f8a99842996d37c2d8b954e0a191/src/scales/constants.ts#L40

This causes issues in charts with a dataset with values less than `1` causing the values to not be shown.

![image](https://user-images.githubusercontent.com/19007109/100131522-c22ab080-2e49-11eb-9368-268e79453631.png)

https://codesandbox.io/s/happy-fog-pkd1j?file=/src/App.tsx

**Describe the solution you'd like**
EC should detect the min value from the data. Also, allow users to set the min log value via settings.

**Describe alternatives you've considered**
Setting explicit min domain value.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/83917

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by th0ger** [comment]
Yes this seems to be related with (if not introduced by) PR #896 

I would also add to the solution in PR #896 , that setting "dummy 1 baseline for log y scale" is not ideal, since there can be values 0<x<1. It would be better to set that baseline value to the minimum of the y-axis (whether that value is found via autoscaling, fixing it by "axis extents" or any other means).

My comments only apply for the log-scale case.

**Comment by nickofthyme** [comment]
Yup totally, this _baseline_ value was added to match the kibana functionality for log scales. I think the intent was to limit the compression of data when most of the data is in a higher order of magnitude while only a few are in a much lower order of magnitude. But really this is hiding potentially valuable data. I could see this as an optional value but not set by default.

**Comment by th0ger** [comment]
Yes, for example in some datasets 0 may be stored like 1e-17 or so due to limited precision of calculations.

But it should be up to the user to set an (optional) lowest value that the ymin autoscaling can obtain. I don't mean a fixed value, but a lowest threshold for the autoscaling.

But in fact, one could simply filter the data for y<y_threshold. So is it really needed?
