### ISSUE TITLE
Crosshair line for Line / Area charts is too light

### ISSUE THREAD

**Issue by miukimiu** [elastic/elastic-charts#925]
**Describe the bug**

The crosshair line for Line/Area charts is too light. There is an open discussion in EUI (https://github.com/elastic/eui/issues/4308).

**To Reproduce**

1. Go to https://elastic.github.io/elastic-charts/?path=/story/line-chart--basic
2. Move the mouse over the line chart
4. The crosshair line is too light 

**Expected behaviour**

The expected behaviour is that the line charts get the `crosshair.line` styles and right now it is getting the `crosshair.band` styles which are too light in color:

https://github.com/elastic/eui/blob/c0b8a25095e9fd60a5a9911d0cb1ba1249400ebf/src/themes/charts/themes.ts#L172-L181

**Screenshots**

<img width="846" alt="Screenshot 2020-11-25 at 12 49 11" src="https://user-images.githubusercontent.com/2750668/100607246-948aaf00-3302-11eb-9819-6a73d49be742.png">
 

**Kibana Cross Issues**

This issue was noticed while working on:
https://github.com/elastic/kibana/pull/81565

**Comment by markov00** [comment]
@miukimiu you are right, the vertical line use the `crosshair.band` for its background color because the `line` theme is used for the horizontal line and should receive a different style (visible when using the tooltip type crosshair as shown here: https://elastic.github.io/elastic-charts/?path=/story/interactions--crosshair-with-time-axis)

I will update the API to support the following:
- line/band as described today but line is used for the vertical line instead of the horizontal one
- crossLine: the style for the horizontal line
